collections:
  projects:
    output: true
    permalink: /projects/:path/
    order:
      - SMG_Waterproofing.md
      - Elixir_Of_Immortality.md
      - Train_Booking_App.md

defaults:
  - scope:
      path: ''
      type: 'authors'
    values:
      layout: 'author'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
    values:
      layout: 'default'

baseurl: 'chalzzy.github.io'
